name: workflow for multiple jobs
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout for repository
              uses: actions/checkout@v4

            - name: second step in first_job
              run: echo "repo is accessed and fetched"

            - name: run script
              run: |
                chmod +x dragon.sh  
                ./dragon.sh
             
            - name: upload dragon file
              uses: actions/upload-artifact@v4
              with: 
                name: upload dragon file
                path: dragon.txt

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps: 
            - name: download dragon file
              uses: actions/download-artifact@v4
              with: 
                name: download dragon file

            - name: test for dragon.txt
              run: grep -i "dragon" dragon.txt
    
                
    third_job:
        needs: second_job
        runs-on: ubuntu-latest
        steps:
            - name: download dragon file
              uses: actions/download-artifact@v4
              with: 
               name: download dragon file

            - name: sample from this job
              run: cat dragon.txt